apiVersion: v2
name: schemabot
description: GitOps for database schemas
type: application
version: 0.1.8
appVersion: "v0.1.3"
maintainers:
  - name: aparajon
    url: https://github.com/aparajon
  - name: morgo
    url: https://github.com/morgo
