// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: tern.proto

package ternv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tern_PullSchema_FullMethodName = "/tern.v1.Tern/PullSchema"
	Tern_Plan_FullMethodName       = "/tern.v1.Tern/Plan"
	Tern_PlanDiff_FullMethodName   = "/tern.v1.Tern/PlanDiff"
	Tern_Apply_FullMethodName      = "/tern.v1.Tern/Apply"
	Tern_Progress_FullMethodName   = "/tern.v1.Tern/Progress"
	Tern_Cutover_FullMethodName    = "/tern.v1.Tern/Cutover"
	Tern_Revert_FullMethodName     = "/tern.v1.Tern/Revert"
	Tern_SkipRevert_FullMethodName = "/tern.v1.Tern/SkipRevert"
	Tern_Health_FullMethodName     = "/tern.v1.Tern/Health"
	Tern_Stop_FullMethodName       = "/tern.v1.Tern/Stop"
	Tern_Cancel_FullMethodName     = "/tern.v1.Tern/Cancel"
	Tern_Start_FullMethodName      = "/tern.v1.Tern/Start"
	Tern_Volume_FullMethodName     = "/tern.v1.Tern/Volume"
)

// TernClient is the client API for Tern service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tern provides schema change planning and execution.
//
// NOTE: require_unimplemented_servers=false is set in buf.gen.yaml.
// Embedding UnimplementedTernServer is optional. We recommend implementing
// all RPCs explicitly so that adding a new RPC causes a compile error
// rather than silently returning "unimplemented".
//
// Lifecycle: Plan -> Apply -> [Progress] -> [Cutover] -> [Revert|SkipRevert]
// Control:   Stop, Start, Volume (can be called during Apply execution)
//
// State machine (per apply):
//
//	pending -> running -> waiting_for_cutover -> cutting_over -> completed
//	             |                                                  |
//	             v                                            revert_window -> reverted
//	           failed                                               |
//	             ^                                                  v
//	           stopped -(Start)-> running                       completed
//
// Only one active schema change per database at a time (enforced by Apply).
type TernClient interface {
	// PullSchema fetches the live schema for a database route and returns it as
	// declarative schema files. It does not modify the database.
	PullSchema(ctx context.Context, in *PullSchemaRequest, opts ...grpc.CallOption) (*PullSchemaResponse, error)
	// Plan generates a schema change plan by diffing declarative schema files
	// against the live database schema. Returns DDL statements needed to converge.
	//
	// This is a stateless operation — it does not modify the database.
	// The returned plan_id is used to invoke Apply.
	//
	// The response includes:
	//   - DDL changes per table (CREATE/ALTER/DROP)
	//   - Unsafe change detection (DROP TABLE, DROP COLUMN, etc.)
	//   - Schema lint warnings
	//   - Errors (e.g., invalid SQL syntax)
	//
	// Errors are returned in the response body (not as RPC errors) so the caller
	// can display them to the user.
	Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	// PlanDiff computes a deployment's desired-vs-live diff without persisting a
	// plan. It is the read-only producer for review-time drift detection: the
	// control plane runs it against every deployment of a database and compares
	// the results to surface a deployment that diverges from the reviewed plan.
	//
	// Unlike Plan, PlanDiff does not create a stored plan record and returns no
	// plan_id — its result is intentionally not applyable. It is idempotent and
	// safe to retry.
	PlanDiff(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanDiffResponse, error)
	// Apply executes a previously generated plan. Returns immediately with an
	// apply_id; execution happens asynchronously. Use Progress to track status.
	//
	// Preconditions:
	//   - Plan must exist (referenced by plan_id).
	//   - No other active schema change for this database (returns accepted=false).
	//
	// Options:
	//   - defer_cutover: If true, pauses at waiting_for_cutover state until
	//     the Cutover RPC is called. If false (default), cutover is automatic.
	//   - allow_unsafe: If true, permits DROP TABLE/COLUMN operations.
	//
	// Execution modes:
	//   - Sequential (default): Each DDL runs independently — copy, cutover, next.
	//     Failure in one DDL cancels remaining DDLs.
	//   - Atomic (defer_cutover=true): All DDLs copy in parallel, then cut over
	//     together. Use for cross-table consistency.
	//
	// Creates Apply and Task records in storage for lifecycle tracking.
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	// Progress returns detailed progress for an active or recently completed
	// schema change. Read-only — does not modify state.
	//
	// Returns per-table progress including rows copied, ETA, percent complete,
	// and a human-readable summary. For Vitess, includes per-shard progress.
	//
	// The overall state is derived from task priority:
	//
	//	running > waiting_for_cutover > cutting_over > pending > stopped > failed > completed
	//
	// Unknown apply IDs return NOT_FOUND.
	Progress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error)
	// Cutover triggers the table swap phase for a schema change that was started
	// with defer_cutover=true. Only valid when state is waiting_for_cutover.
	//
	// In atomic mode, all tables cut over together. In sequential mode, the
	// current table cuts over (subsequent tables proceed automatically).
	//
	// No-op if defer_cutover was not used (cutover happens automatically).
	Cutover(ctx context.Context, in *CutoverRequest, opts ...grpc.CallOption) (*CutoverResponse, error)
	// Revert rolls back a completed schema change to the original schema.
	// Only valid during the revert window (state = revert_window).
	//
	// Transitions: revert_window -> reverted.
	//
	// After the revert window expires, the schema change is finalized and
	// can no longer be reverted.
	Revert(ctx context.Context, in *RevertRequest, opts ...grpc.CallOption) (*RevertResponse, error)
	// SkipRevert closes the revert window early and finalizes the schema change.
	// Only valid when state is revert_window.
	//
	// Transitions: revert_window -> completed.
	//
	// Call this when you are confident the schema change is correct and want to
	// skip the monitoring period.
	SkipRevert(ctx context.Context, in *SkipRevertRequest, opts ...grpc.CallOption) (*SkipRevertResponse, error)
	// Health checks service health by verifying storage connectivity.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Stop pauses all non-terminal tasks for a schema change.
	//
	// Transitions: any non-terminal state -> stopped.
	//
	// For MySQL (Spirit engine): The user has limited time to resume based on
	// binlog retention (default 7 days). After that, the checkpoint expires
	// and the schema change cannot be resumed.
	//
	// Returns stopped_count and skipped_count to indicate how many tasks
	// were affected.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// Cancel terminates a schema change permanently.
	//
	// Transitions: any non-terminal state -> cancelled.
	//
	// For engines where stop is already permanent, cancel uses the same engine
	// control operation and records the final state as cancelled.
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// Start resumes a previously stopped schema change from its checkpoint.
	//
	// Transitions: stopped -> running.
	//
	// Preconditions:
	//   - At least one stopped task must exist for the database.
	//   - For MySQL: binlog must not have expired (default 7 day window).
	//
	// Execution resumes asynchronously (same as Apply). Use Progress to track.
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Volume adjusts the schema change speed/concurrency while running.
	//
	// Scale: 1 (conservative, minimal database load) to 11 (aggressive, maximum
	// throughput). Affects chunk size, lock hold time, and throttle parameters.
	//
	// Can be called multiple times during a running schema change. The engine
	// is stopped and restarted internally to apply the new settings.
	//
	// Preconditions:
	//   - Active schema change must exist for the database.
	//   - Volume must be 1-11 inclusive.
	Volume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*VolumeResponse, error)
}

type ternClient struct {
	cc grpc.ClientConnInterface
}

func NewTernClient(cc grpc.ClientConnInterface) TernClient {
	return &ternClient{cc}
}

func (c *ternClient) PullSchema(ctx context.Context, in *PullSchemaRequest, opts ...grpc.CallOption) (*PullSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullSchemaResponse)
	err := c.cc.Invoke(ctx, Tern_PullSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, Tern_Plan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) PlanDiff(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanDiffResponse)
	err := c.cc.Invoke(ctx, Tern_PlanDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, Tern_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) Progress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressResponse)
	err := c.cc.Invoke(ctx, Tern_Progress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) Cutover(ctx context.Context, in *CutoverRequest, opts ...grpc.CallOption) (*CutoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CutoverResponse)
	err := c.cc.Invoke(ctx, Tern_Cutover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) Revert(ctx context.Context, in *RevertRequest, opts ...grpc.CallOption) (*RevertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevertResponse)
	err := c.cc.Invoke(ctx, Tern_Revert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) SkipRevert(ctx context.Context, in *SkipRevertRequest, opts ...grpc.CallOption) (*SkipRevertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkipRevertResponse)
	err := c.cc.Invoke(ctx, Tern_SkipRevert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Tern_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, Tern_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, Tern_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, Tern_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ternClient) Volume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*VolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VolumeResponse)
	err := c.cc.Invoke(ctx, Tern_Volume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TernServer is the server API for Tern service.
// All implementations should embed UnimplementedTernServer
// for forward compatibility.
//
// Tern provides schema change planning and execution.
//
// NOTE: require_unimplemented_servers=false is set in buf.gen.yaml.
// Embedding UnimplementedTernServer is optional. We recommend implementing
// all RPCs explicitly so that adding a new RPC causes a compile error
// rather than silently returning "unimplemented".
//
// Lifecycle: Plan -> Apply -> [Progress] -> [Cutover] -> [Revert|SkipRevert]
// Control:   Stop, Start, Volume (can be called during Apply execution)
//
// State machine (per apply):
//
//	pending -> running -> waiting_for_cutover -> cutting_over -> completed
//	             |                                                  |
//	             v                                            revert_window -> reverted
//	           failed                                               |
//	             ^                                                  v
//	           stopped -(Start)-> running                       completed
//
// Only one active schema change per database at a time (enforced by Apply).
type TernServer interface {
	// PullSchema fetches the live schema for a database route and returns it as
	// declarative schema files. It does not modify the database.
	PullSchema(context.Context, *PullSchemaRequest) (*PullSchemaResponse, error)
	// Plan generates a schema change plan by diffing declarative schema files
	// against the live database schema. Returns DDL statements needed to converge.
	//
	// This is a stateless operation — it does not modify the database.
	// The returned plan_id is used to invoke Apply.
	//
	// The response includes:
	//   - DDL changes per table (CREATE/ALTER/DROP)
	//   - Unsafe change detection (DROP TABLE, DROP COLUMN, etc.)
	//   - Schema lint warnings
	//   - Errors (e.g., invalid SQL syntax)
	//
	// Errors are returned in the response body (not as RPC errors) so the caller
	// can display them to the user.
	Plan(context.Context, *PlanRequest) (*PlanResponse, error)
	// PlanDiff computes a deployment's desired-vs-live diff without persisting a
	// plan. It is the read-only producer for review-time drift detection: the
	// control plane runs it against every deployment of a database and compares
	// the results to surface a deployment that diverges from the reviewed plan.
	//
	// Unlike Plan, PlanDiff does not create a stored plan record and returns no
	// plan_id — its result is intentionally not applyable. It is idempotent and
	// safe to retry.
	PlanDiff(context.Context, *PlanRequest) (*PlanDiffResponse, error)
	// Apply executes a previously generated plan. Returns immediately with an
	// apply_id; execution happens asynchronously. Use Progress to track status.
	//
	// Preconditions:
	//   - Plan must exist (referenced by plan_id).
	//   - No other active schema change for this database (returns accepted=false).
	//
	// Options:
	//   - defer_cutover: If true, pauses at waiting_for_cutover state until
	//     the Cutover RPC is called. If false (default), cutover is automatic.
	//   - allow_unsafe: If true, permits DROP TABLE/COLUMN operations.
	//
	// Execution modes:
	//   - Sequential (default): Each DDL runs independently — copy, cutover, next.
	//     Failure in one DDL cancels remaining DDLs.
	//   - Atomic (defer_cutover=true): All DDLs copy in parallel, then cut over
	//     together. Use for cross-table consistency.
	//
	// Creates Apply and Task records in storage for lifecycle tracking.
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	// Progress returns detailed progress for an active or recently completed
	// schema change. Read-only — does not modify state.
	//
	// Returns per-table progress including rows copied, ETA, percent complete,
	// and a human-readable summary. For Vitess, includes per-shard progress.
	//
	// The overall state is derived from task priority:
	//
	//	running > waiting_for_cutover > cutting_over > pending > stopped > failed > completed
	//
	// Unknown apply IDs return NOT_FOUND.
	Progress(context.Context, *ProgressRequest) (*ProgressResponse, error)
	// Cutover triggers the table swap phase for a schema change that was started
	// with defer_cutover=true. Only valid when state is waiting_for_cutover.
	//
	// In atomic mode, all tables cut over together. In sequential mode, the
	// current table cuts over (subsequent tables proceed automatically).
	//
	// No-op if defer_cutover was not used (cutover happens automatically).
	Cutover(context.Context, *CutoverRequest) (*CutoverResponse, error)
	// Revert rolls back a completed schema change to the original schema.
	// Only valid during the revert window (state = revert_window).
	//
	// Transitions: revert_window -> reverted.
	//
	// After the revert window expires, the schema change is finalized and
	// can no longer be reverted.
	Revert(context.Context, *RevertRequest) (*RevertResponse, error)
	// SkipRevert closes the revert window early and finalizes the schema change.
	// Only valid when state is revert_window.
	//
	// Transitions: revert_window -> completed.
	//
	// Call this when you are confident the schema change is correct and want to
	// skip the monitoring period.
	SkipRevert(context.Context, *SkipRevertRequest) (*SkipRevertResponse, error)
	// Health checks service health by verifying storage connectivity.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Stop pauses all non-terminal tasks for a schema change.
	//
	// Transitions: any non-terminal state -> stopped.
	//
	// For MySQL (Spirit engine): The user has limited time to resume based on
	// binlog retention (default 7 days). After that, the checkpoint expires
	// and the schema change cannot be resumed.
	//
	// Returns stopped_count and skipped_count to indicate how many tasks
	// were affected.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// Cancel terminates a schema change permanently.
	//
	// Transitions: any non-terminal state -> cancelled.
	//
	// For engines where stop is already permanent, cancel uses the same engine
	// control operation and records the final state as cancelled.
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	// Start resumes a previously stopped schema change from its checkpoint.
	//
	// Transitions: stopped -> running.
	//
	// Preconditions:
	//   - At least one stopped task must exist for the database.
	//   - For MySQL: binlog must not have expired (default 7 day window).
	//
	// Execution resumes asynchronously (same as Apply). Use Progress to track.
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// Volume adjusts the schema change speed/concurrency while running.
	//
	// Scale: 1 (conservative, minimal database load) to 11 (aggressive, maximum
	// throughput). Affects chunk size, lock hold time, and throttle parameters.
	//
	// Can be called multiple times during a running schema change. The engine
	// is stopped and restarted internally to apply the new settings.
	//
	// Preconditions:
	//   - Active schema change must exist for the database.
	//   - Volume must be 1-11 inclusive.
	Volume(context.Context, *VolumeRequest) (*VolumeResponse, error)
}

// UnimplementedTernServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTernServer struct{}

func (UnimplementedTernServer) PullSchema(context.Context, *PullSchemaRequest) (*PullSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullSchema not implemented")
}
func (UnimplementedTernServer) Plan(context.Context, *PlanRequest) (*PlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Plan not implemented")
}
func (UnimplementedTernServer) PlanDiff(context.Context, *PlanRequest) (*PlanDiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanDiff not implemented")
}
func (UnimplementedTernServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedTernServer) Progress(context.Context, *ProgressRequest) (*ProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Progress not implemented")
}
func (UnimplementedTernServer) Cutover(context.Context, *CutoverRequest) (*CutoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cutover not implemented")
}
func (UnimplementedTernServer) Revert(context.Context, *RevertRequest) (*RevertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Revert not implemented")
}
func (UnimplementedTernServer) SkipRevert(context.Context, *SkipRevertRequest) (*SkipRevertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SkipRevert not implemented")
}
func (UnimplementedTernServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTernServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedTernServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedTernServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedTernServer) Volume(context.Context, *VolumeRequest) (*VolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Volume not implemented")
}
func (UnimplementedTernServer) testEmbeddedByValue() {}

// UnsafeTernServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TernServer will
// result in compilation errors.
type UnsafeTernServer interface {
	mustEmbedUnimplementedTernServer()
}

func RegisterTernServer(s grpc.ServiceRegistrar, srv TernServer) {
	// If the following call panics, it indicates UnimplementedTernServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tern_ServiceDesc, srv)
}

func _Tern_PullSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).PullSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_PullSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).PullSchema(ctx, req.(*PullSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_Plan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).Plan(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_PlanDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).PlanDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_PlanDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).PlanDiff(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_Progress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).Progress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_Progress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).Progress(ctx, req.(*ProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_Cutover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CutoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).Cutover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_Cutover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).Cutover(ctx, req.(*CutoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_Revert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).Revert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_Revert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).Revert(ctx, req.(*RevertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_SkipRevert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkipRevertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).SkipRevert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_SkipRevert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).SkipRevert(ctx, req.(*SkipRevertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tern_Volume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TernServer).Volume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tern_Volume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TernServer).Volume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tern_ServiceDesc is the grpc.ServiceDesc for Tern service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tern_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tern.v1.Tern",
	HandlerType: (*TernServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullSchema",
			Handler:    _Tern_PullSchema_Handler,
		},
		{
			MethodName: "Plan",
			Handler:    _Tern_Plan_Handler,
		},
		{
			MethodName: "PlanDiff",
			Handler:    _Tern_PlanDiff_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _Tern_Apply_Handler,
		},
		{
			MethodName: "Progress",
			Handler:    _Tern_Progress_Handler,
		},
		{
			MethodName: "Cutover",
			Handler:    _Tern_Cutover_Handler,
		},
		{
			MethodName: "Revert",
			Handler:    _Tern_Revert_Handler,
		},
		{
			MethodName: "SkipRevert",
			Handler:    _Tern_SkipRevert_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Tern_Health_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Tern_Stop_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Tern_Cancel_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Tern_Start_Handler,
		},
		{
			MethodName: "Volume",
			Handler:    _Tern_Volume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tern.proto",
}
