#!/usr/bin/env python3
"""Insert or refresh a Table of Contents in each Markdown file under docs/.

Run via `make docs-toc` (see Makefile).

For each file, the TOC lists H2 and H3 headings (skipping headings inside
fenced code blocks), uses GitHub-style slug anchors, and is placed
immediately after the leading H1. The block is wrapped in BEGIN/END markers
so a re-run replaces it in place instead of appending a duplicate. Run this
after adding or renaming headings in any doc.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

BEGIN = "<!-- BEGIN TOC (auto-generated by `make docs-toc`) -->"
END = "<!-- END TOC (auto-generated by `make docs-toc`) -->"


def slugify(text: str) -> str:
    # GitHub's slugger: lowercase, drop punctuation except `-` and `_`,
    # collapse whitespace to single `-`. Underscores are preserved because
    # GitHub treats them as word characters in heading anchors.
    text = text.strip().lower()
    text = re.sub(r"[^\w\s\-]", "", text, flags=re.UNICODE)
    text = re.sub(r"\s+", "-", text)
    return text


def parse_headings(lines: list[str]) -> list[tuple[int, str]]:
    headings: list[tuple[int, str]] = []
    in_fence = False
    for line in lines:
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = re.match(r"^(#{2,3})\s+(.+?)\s*$", line)
        if m:
            headings.append((len(m.group(1)), m.group(2)))
    return headings


def build_toc(headings: list[tuple[int, str]]) -> str:
    if not headings:
        return ""
    lines = ["## Table of Contents", ""]
    slug_counts: dict[str, int] = {}
    for level, text in headings:
        slug = slugify(text)
        count = slug_counts.get(slug, 0)
        slug_counts[slug] = count + 1
        anchor = slug if count == 0 else f"{slug}-{count}"
        indent = "  " * (level - 2)
        lines.append(f"{indent}- [{text}](#{anchor})")
    lines.append("")
    return "\n".join(lines)


def process(path: Path) -> bool:
    original = path.read_text()

    # Strip any existing auto-generated TOC block (matches the current and
    # any prior marker text so re-runs after a marker change still work).
    text = re.sub(
        r"<!-- BEGIN TOC[^>]*-->.*?<!-- END TOC[^>]*-->\n*",
        "",
        original,
        flags=re.DOTALL,
    )
    lines = text.splitlines()

    headings = parse_headings(lines)
    toc_body = build_toc(headings)
    if not toc_body:
        return False

    # Insert after the leading H1 (and its trailing blank line, if any).
    insert_at = 0
    for i, line in enumerate(lines):
        if line.startswith("# "):
            insert_at = i + 1
            if insert_at < len(lines) and lines[insert_at].strip() == "":
                insert_at += 1
            break

    block = [BEGIN, "", toc_body.rstrip(), "", END, ""]
    new_lines = lines[:insert_at] + block + lines[insert_at:]
    new_text = "\n".join(new_lines)
    if not new_text.endswith("\n"):
        new_text += "\n"

    if new_text == original:
        return False
    path.write_text(new_text)
    return True


def main(argv: list[str]) -> int:
    paths = [Path(p) for p in argv[1:]]
    if not paths:
        paths = sorted(Path("docs").glob("*.md"))
    changed = 0
    for p in paths:
        if process(p):
            print(f"updated {p}")
            changed += 1
    print(f"{changed} file(s) updated")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
