CREATE TABLE `apply_operations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `apply_id` bigint unsigned NOT NULL,
  `deployment` varchar(255) NOT NULL,
  `operation_key` varchar(255) NOT NULL DEFAULT '',
  `operation_kind` varchar(32) NOT NULL DEFAULT 'work',
  `target` varchar(255) NOT NULL DEFAULT '',
  `engine_resume_context` varchar(255) DEFAULT NULL,
  `engine_resume_metadata` json DEFAULT NULL,
  `state` varchar(100) NOT NULL DEFAULT 'pending',
  `error_message` text,
  `cutover_policy` varchar(16) NOT NULL DEFAULT 'rolling',
  `on_failure` varchar(16) NOT NULL DEFAULT 'halt',
  `lease_owner` varchar(255) NOT NULL DEFAULT '',
  `lease_token` varchar(64) NOT NULL DEFAULT '',
  `lease_acquired_at` datetime DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_apply_operation` (`apply_id`,`deployment`,`operation_key`),
  KEY `idx_deployment_state` (`deployment`,`state`),
  KEY `idx_state_created_id` (`state`,`created_at`,`id`),
  KEY `idx_apply_created_id` (`apply_id`,`created_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
