CREATE TABLE `applies` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `apply_identifier` varchar(255) NOT NULL,
  `lock_id` bigint unsigned NOT NULL,
  `plan_id` bigint unsigned NOT NULL,
  `database_name` varchar(255) NOT NULL,
  `database_type` varchar(50) NOT NULL,
  `repository` varchar(255) NOT NULL,
  `pull_request` int unsigned NOT NULL,
  `environment` varchar(50) NOT NULL,
  `deployment` varchar(255) NOT NULL DEFAULT '',
  `caller` varchar(255) NOT NULL DEFAULT '',
  `installation_id` bigint NOT NULL DEFAULT '0',
  `external_id` varchar(255) NOT NULL DEFAULT '',
  `engine` varchar(50) NOT NULL,
  `state` varchar(100) NOT NULL,
  `error_message` text,
  `options` json NOT NULL,
  `attempt` int NOT NULL DEFAULT '0',
  `lease_owner` varchar(255) NOT NULL DEFAULT '',
  `lease_token` varchar(64) NOT NULL DEFAULT '',
  `lease_acquired_at` datetime DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_apply_identifier` (`apply_identifier`),
  KEY `idx_lock_id` (`lock_id`),
  KEY `idx_plan_id` (`plan_id`),
  KEY `idx_database_env` (`database_name`,`database_type`,`environment`),
  KEY `idx_database_env_deployment` (`database_name`,`database_type`,`environment`,`deployment`),
  KEY `idx_repo_pr` (`repository`,`pull_request`),
  KEY `idx_created_id` (`created_at`,`id`),
  KEY `idx_environment_created_id` (`environment`,`created_at`,`id`),
  KEY `idx_state_created_id` (`state`,`created_at`,`id`),
  KEY `idx_environment_state_created_id` (`environment`,`state`,`created_at`,`id`),
  KEY `idx_completed_at_state` (`completed_at`,`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
